name: CI
on:
  push: {branches: [ main, master ]}
  pull_request: {branches: [ main, master ]}
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: {python-version: [ '3.10', '3.11', '3.12' ]}
    env:
      SECRET_KEY: "test-secret-key-for-ci-pipeline-should-be-at-least-32-chars"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Run linting
        run: uv run ruff check .
      - name: Run formatting check
        run: uv run ruff format --check .
      - name: Run type checking
        run: uv run mypy app tests
      - name: Run tests
        run: uv run pytest -q
